### PR TITLE
Fix bug #65

### LINKED ISSUE #65: Bug Report: panic in parsing version
image

Panic at
```
        let sem_ver = semver::Version::parse(&cur_release.version)
            .unwrap_or_else(|_| panic!("failed to parse version {}", &cur_release.version));
```

### PR DESCRIPTION
**Pull request by xizheyin**
Fix #65

### CODE REVIEW

File: repo_import/src/version_info.rs [hunk 1]
```diff
@@ -78,11 +78,11 @@ impl ImportContext {
...
 
-                let dependencies = self
-                    .parse_a_package_of_a_version(content, git_url, tag_name)
-                    .unwrap_or_default();
-
-                res.push(dependencies);
+                if let Some(dependencies) =
+                    self.parse_a_package_of_a_version(content, git_url, tag_name)
+                {
+                    res.push(dependencies);
```
Comment (xizheyin) [inline repo_import/src/version_info.rs:84]: This is the cause of #65

**Review by benjamin-747 — APPROVED** [review]
